global: # 全局配置
  resolve_timeout: 5m                 # 处理超时时间，默认为5min
  #smtp_from: '*****@qq.com'          # QQ邮件发送地址
  #smtp_smarthost: 'smtp.qq.com:465'  # QQ邮箱SMTP 服务地址
  smtp_from: '*****@163.com'          # 网易邮件发送地址
  smtp_smarthost: 'smtp.163.com:25'   # 网易邮箱SMTP 服务地址
  smtp_auth_username: '*****'         # 邮件发送地址用户名
  smtp_auth_password: '*****'         # 邮件发送地址授权码
  smtp_require_tls: false
  smtp_hello: 'qq.com'
route:  # 设置报警的分发策略
  group_by: ['alertname']
  group_wait: 20s           # 最初即第一次等待多久时间发送一组警报的通知
  group_interval: 5m        # 在发送新警报前的等待时间
  repeat_interval: 5m       # 发送重复警报的周期 对于email配置中，此项不可以设置过低，否则将会由于邮件发送太多频繁，被smtp服务器拒绝
  receiver: 'email'
receivers:                  # 配置告警消息接受者信息
- name: 'email'
  email_configs:
  - to: '*****@qq.com'      #邮件接收地址,不能跟 smtp_from 的邮箱名字重复
    send_resolved: true
inhibit_rules:              # 抑制规则配置
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

