version: '2'
services:
  mysql:
    image: mysql:latest                                           # 镜像`mysql:latest`
    container_name: mysql                                         # 容器名称'mysql'
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                                                      # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "/data/docker/mysql/conf/my.cnf:/etc/my.cnf"
      - "/data/docker/mysql/data:/var/lib/mysql"
      - "/data/docker/mysql/logs:/var/log/mysql"
    environment:                          # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 123123         # 设置root用户密码
    ports:                                # 映射端口
      - "3306:3306"
