version: '3'
services:
  redis:
    image: redis:latest                                                                 # 镜像`redis:latest`
    container_name: redis                                                               # 容器名称'redis'
    restart: unless-stopped                                                             # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    command: redis-server /etc/redis/redis.conf --requirepass 123123 --appendonly no    # 启动redis服务并设置密码为123123，默认不开启redis-aof方式持久化配置
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "/data/docker/redis/data:/data"
      - "/data/docker/redis/conf/redis.conf:/etc/redis/redis.conf"
    ports:                              # 映射端口
      - "6379:6379"
